name: Node.js CI & Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

# Эта переменная уберет предупреждения для всех заданий
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build_and_test:
    runs-on: windows-latest
    # ... остальная часть вашего job ...
