name: Node.js CI & Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Разрешаем воркфлоу делать публикации на GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Исключаем одновременные деплои
concurrency:
  group: "pages"
  cancel-in-progress: false

# Эта переменная убирает предупреждения об устаревшем Node.js 20 в действиях
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build_and_test:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build (if present)
        run: npm run build --if-present

      - name: Test
        run: npm test

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    # Деплой запустится ТОЛЬКО если тесты на Windows прошли успешно и это ветка main
    needs: build_and_test
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Собираем статические файлы проекта для публикации
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Загружаем корень репозитория, где лежит index.html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
